openapi: 3.0.0
info:
  title: Feature flag API
  version: 1.0.0
  description: This is API contract for feature flag service.
paths:
  /feature-flags:
    get:
      summary: Get all feature flags
      description: Returns a list of all feature flags in the system
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feature-flag'
    post:
      summary: Create a new feature flag
      description: Creates a new feature flag in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feature-flag'
      responses:
        '201':
          description: Successful response
  /feature-flags/{flagId}:
    get:
      summary: Get a feature flag by ID
      description: Returns a specific feature flag based on ID
      parameters:
        - name: flagId
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feature-flag'
        '404':
          description: feature flag not found
        '400':
          description: Invalid feature flag Id supplied
    put:
      summary: Update a feature flag by ID
      description: Updates a specific feature flag based on ID
      parameters:
        - name: flagId
          in: path
          required: true
          description: ID of the feature flag
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feature-flag'
      responses:
        '200':
          description: Successful response
    delete:
      summary: Delete a feature flag by ID
      description: Deletes a specific feature flag based on ID
      parameters:
        - name: flagId
          in: path
          required: true
          description: ID of the feature flag
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /users/feature-flags/:
    get: 
      summary: Lists all the feature flags for the user
      description: Shows the feature flag for a user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/ApiResponses/Feature-flags'
  /users/userId/{userId}:
    get:
      summary: Get all data about User
      description: Fetches all details about the user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the feature flag
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Users'
  /users/userId/{userId}/feature-flag/{flagId}:
    get:
      summary: Get feature flag for user
      description: Get if the flag is set for the user
      parameters:
        - name: userId
          in: path
          required: true
          description: Id of user
          schema: 
            type: string
        - name: flagId
          in: path
          required: true
          description: Id of the flag
          schema: 
            type: string
      responses:
        '200':
          description: Successful response
          content: 
            application/json:
              schema: 
                $ref: '#/ApiResponses/User-feature-flag-response'
    post:
      summary: To enable feature flag for a user
      parameters:
        - name: userId
          in: path
          required: true
          description: Id of user
          schema: 
            type: 
              string
        - name: flagId
          in: path
          required: true
          description: Id of the flag
          schema: 
            type: string
      responses:
        '201':
          description: Created successful

          
       
components:
  schemas:
    Feature-flag:
      type: object
      properties:
        id: 
          type: string
        name: 
          type: string
        description:
          type: string
        createdBy:
          type: string
        createdAt:
          type: integer
    Users:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: number
        yoe: 
          type: number
        company: 
          type: string
        designation:
          type: string
        img: 
          type: string
        github_id:
          type: string
        linkedin_id:
          type: string
        twitter_id:
          type: string
        instagram_id:
          type: string
        skills:
          type: array
          items: 
            type: string
        website:
          type: string
        github_display_name:
          type: string
        isMember: 
          type: boolean
        userType:
          type: string
        status: 
          type: string
        flagIds:
          type: array
          items: 
            type: string
ApiResponses:
  Feature-flags:
    type: object
    properties:
      id:
        type: string
      feature-flags:
        type: array
        items: 
          type: string
          
  User-feature-flag-response:
    type: object
    properties:
      userId:
        type: string
      flagId: 
        type: string
      enabled: 
        type: boolean
        
        
